package fileapi

import (
	"errors"
	"syscall"
)

var (
	kernel32 = syscall.NewLazyDLL("kernel32.dll")

	findFirstVolumeWProc                  = kernel32.NewProc("FindFirstVolumeW")
	findNextVolumeWProc                   = kernel32.NewProc("FindNextVolumeW")
	findVolumeCloseProc                   = kernel32.NewProc("FindVolumeClose")
	getVolumePathNamesForVolumeNameWProc  = kernel32.NewProc("GetVolumePathNamesForVolumeNameW")
	procGetVolumeNameForVolumeMountPointW = kernel32.NewProc("GetVolumeNameForVolumeMountPointW")
	getDriveTypeWProc                     = kernel32.NewProc("GetDriveTypeW")
	procGetVolumeInformationW             = kernel32.NewProc("GetVolumeInformationW")
	procGetLogicalDrives                  = kernel32.NewProc("GetLogicalDrives")
	procDeleteVolumeMountPointW           = kernel32.NewProc("DeleteVolumeMountPointW")
	procGetDriveTypeW                     = kernel32.NewProc("GetDriveTypeW")
	procDeleteFileW                       = kernel32.NewProc("DeleteFileW")
	createFileW                           = kernel32.NewProc("CreateFileW")
	createFile2Proc                       = kernel32.NewProc("CreateFile2")
	procCreateDirectoryW                  = kernel32.NewProc("CreateDirectoryW")
	areFileApisANSIProc                   = kernel32.NewProc("AreFileApisANSI")
	fileTimeToLocalFileTimeProc           = kernel32.NewProc("FileTimeToLocalFileTime")
	findCloseProc                         = kernel32.NewProc("FindClose")
	findFirstFileExWProc                  = kernel32.NewProc("FindFirstFileExW")
	findFirstFileNameWProc                = kernel32.NewProc("FindFirstFileNameW")
	findFirstFileWProc                    = kernel32.NewProc("FindFirstFileW")
	findFirstStreamWProc                  = kernel32.NewProc("FindFirstStreamW")
	findNextFileWProc                     = kernel32.NewProc("FindNextFileW")
	findNextStreamWProc                   = kernel32.NewProc("FindNextStreamW")
	getDiskFreeSpaceExWProc               = kernel32.NewProc("GetDiskFreeSpaceExW")
	getDiskFreeSpaceWProc                 = kernel32.NewProc("GetDiskFreeSpaceW")
	getFileAttributesExWProc              = kernel32.NewProc("GetFileAttributesExW")
	getFileAttributesWProc                = kernel32.NewProc("GetFileAttributesW")
	getFileSizeProc                       = kernel32.NewProc("GetFileSize")
	getFileSizeExProc                     = kernel32.NewProc("GetFileSizeEx")
	getFileTimeProc                       = kernel32.NewProc("GetFileTime")
	getFileTypeProc                       = kernel32.NewProc("GetFileType")
	getFinalPathNameByHandleWProc         = kernel32.NewProc("GetFinalPathNameByHandleW")
	getFullPathNameWProc                  = kernel32.NewProc("GetFullPathNameW")
	getLogicalDriveStringsWProc           = kernel32.NewProc("GetLogicalDriveStringsW")
	getLongPathNameWProc                  = kernel32.NewProc("GetLongPathNameW")
	getShortPathNameWProc                 = kernel32.NewProc("GetShortPathNameW")
	localFileTimeToFileTimeProc           = kernel32.NewProc("LocalFileTimeToFileTime")
	readFileProc                          = kernel32.NewProc("ReadFile")
	readFileExProc                        = kernel32.NewProc("ReadFileEx")
	setFileTimeProc                       = kernel32.NewProc("SetFileTime")
	writeFileProc                         = kernel32.NewProc("WriteFile")

	errUnknownDriveType = errors.New("unknown drive type")
	errNoRootDir        = errors.New("invalid root drive path")
)
